CREATE TABLE QUESTIONARI_MANAGEMENT_QUESTIONARIE
(
  ID INT PRIMARY KEY NOT NULL,
  Title VARCHAR(255) NOT NULL,
  ID_user VARCHAR(255) NOT NULL,
  Create_date DATETIME NOT NULL,
  Allow_questionarie_yn BOOLEAN DEFAULT "true"
);

CREATE TABLE QUESTIONARI_MANAGEMENT_QUESTIONS
(
  ID INT PRIMARY KEY NOT NULL,
  ID_Questionarie INT NOT NULL,
  Text_content TEXT NOT NULL,
  Allow_question_yn BOOLEAN DEFAULT "true"
);

CREATE TABLE QUESTIONARI_MANAGEMENT_ANSWERS
(
  ID INT PRIMARY KEY NOT NULL,
  ID_Question INT NOT NULL,
  Text_content TEXT NOT NULL,
  Allow_answer_yn BOOLEAN DEFAULT "true"
);

CREATE TABLE QUESTIONARI_MANAGEMENT_RESULTS
(
  ID INT PRIMARY KEY NOT NULL,
  ID_Questionarie INT NOT NULL,
  Text_content TEXT NOT NULL,
  Score_range INT NOT NULL
);

CREATE TABLE QUESTIONARI_MANAGEMENT_CATEGORIES
(
  ID INT PRIMARY KEY NOT NULL,
  Name VARCHAR(255) NOT NULL
);

CREATE TABLE QUESTIONARI_MANAGEMENT_RELATIONS
(
  ID INT PRIMARY KEY NOT NULL,
  ID_Questionarie INT NOT NULL,
  ID_Category INT NOT NULL
);
